// Copies JetBrains Mono (the Console's only face, as on reqall.net) from
// @fontsource into assets/fonts and writes fonts.css. The renderer's CSP
// allows only local resources, so the font ships with the app instead of
// loading from Google Fonts. There is no unicode-range: the console leans
// on arrows and box-drawing glyphs, so the browser should take whatever the
// file has and fall back per glyph. Run: npm run fonts

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const out = path.join(root, 'assets', 'fonts')
const FACES = [{ pkg: 'jetbrains-mono', family: 'JetBrains Mono', weights: [400, 500, 600, 700] }]

fs.mkdirSync(out, { recursive: true })
let css = '/* Generated by scripts/sync-fonts.mjs from @fontsource (SIL OFL 1.1). Do not edit. */\n'
for (const face of FACES) {
  const dir = path.join(root, 'node_modules', '@fontsource', face.pkg)
  fs.copyFileSync(path.join(dir, 'LICENSE'), path.join(out, `LICENSE-${face.pkg}.txt`))
  for (const weight of face.weights) {
    const file = `${face.pkg}-latin-${weight}-normal.woff2`
    fs.copyFileSync(path.join(dir, 'files', file), path.join(out, file))
    css += `@font-face { font-family: '${face.family}'; font-style: normal; font-weight: ${weight}; font-display: swap; src: url(./${file}) format('woff2'); }\n`
  }
}
fs.writeFileSync(path.join(out, 'fonts.css'), css)
console.log(`wrote ${out}`)
